### ISSUE TITLE
Comparison of Numerical, Date and Boolean types are broken

### ISSUE THREAD

**Issue by haohong** [ydaniv/django-rest-assured#27]
Because it casts the response data to text in default, the comparisons for numerical, date, and boolean types are failing.
Ex:
```
self.assertEqual(value, text_type(data[attr]))
E   AssertionError: 10032 != '10032'

self.assertEqual(value, text_type(data[attr]))
E   AssertionError: '2017-03-13 12:21:13.796885+00:00' != '2017-03-13T12:21:13+0000'

self.assertEqual(value, text_type(data[attr]))
E   AssertionError: False != 'False'
```

I think we should determine the type of fields instead of simply casting into text.

**Comment by ydaniv** [comment]
Hi @haohong, thanks for the input! You're probably hitting this because you're using `test_detail` and have `list`s or `tuple`s in your `attributes_to_check` [here](https://github.com/ydaniv/django-rest-assured/blob/master/rest_assured/testcases.py#L202). So, eventually, the value is not necessarily a string.
Is that correct?

**Comment by haohong** [comment]
@ydaniv yes, that's correct.

**Comment by ydaniv** [comment]
Yes, that is a bug. I think I'll just add the string casting there to conform with the rest of the code - unless there's some objection, which I'll gladly listen to.

**Comment by haohong** [comment]
@ydaniv Thanks
