### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fmarco** [ydaniv/django-rest-assured#33]
when? :)

**Comment by ydaniv** [comment]
(:
Actually nothing was changed, we just fixed the tests on CI, so you can use it as is, although there was one PR merged that just added printing of mismatching attributes.

I'll update readme soon.

**Comment by westurner** [comment]
https://github.com/ydaniv/django-rest-assured/commit/a0056166c864128bf47546840bdb2072f0378a39 appears to be necessary for Django 3.0 support?

**Comment by ydaniv** [comment]
@westurner that one merged, so what else is missing?

**Comment by westurner** [comment]
Hopefully I will have time to take a further look later this week. After
following the tutorial in the docs, I was getting NoReverseMatch errors
which I assumed were due to URL registration on my end.

"Release often"?:
https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.travis.yml#L21

**Comment by owurman** [comment]
Is the six package fix going to be in a release soon? 0.2.1 does not work with Django 3.

**Comment by ydaniv** [comment]
Oh 😮 my bad, it's not released indeed! I'll publish a new one.
@westurner waiting for your input as well 🙏

**Comment by westurner** [comment]
I would say go ahead and release if the existing tests pass?

Here's an easy manual `make release` script:
https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L84-L90

The .travis.yml linked above does auto-publish to PyPI when tox runs w/ no errors; in order to release early and often.
https://en.wikipedia.org/wiki/Release_early,_release_often

**Comment by westurner** [comment]
The compatible versions listed in the README need to be updated, too.

**Comment by owurman** [comment]
Ping on this? It would be lovely to be able to run my unit tests again. Anything I can pitch in to help with?

**Comment by westurner** [comment]
When you install the master branch (containing the unreleased changes,) as editable with pip, do the tests run as they did before?

```bash
pip install -e git+https://github.com/ydaniv/django-rest-assured@master#egg=django-rest-assured
```

**Comment by owurman** [comment]
Yes, with the unreleased changes, my tests all pass.

**Comment by ydaniv** [comment]
@westurner @owurman glad to say I managed to wipe the dust off and publish 0.2.3 🎉 🥳  🎉 
(0.2.2 was missing long description on pypi).
Closing this for now.
Thank ya'll!
